### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by KyYYyK** [KyYYyK/Homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by KyYYyKer** [comment]
2002 год
Рождение меня как человека

2004 год (не помню точно)
садик и прочая сладкая детская фигня

2007 год
первый раз в первый класс

2012-2017 год
ОЧЕНЬ громкие и большие успехи в спорте

2019 год
закончена учёба и успешное поступление
