### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by KyYYyK** [KyYYyK/Homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by KyYYyKer** [comment]
Ну пришёл я сюда вообще для программирования на .net) не сильно люблю вебку, но куда же без неё. Из сильных сторон есть то что я всегда пытаюсь доделать работу до конца, может быть не всегда вовремя (это кстати плохая сторона), но всегда делаю. Хобби... ну тут всё просто я на спортике, каратэ ван лав)
